### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by fosskingdom** [slavabarkov/tidy#21]
[LOG]
java.lang.NullPointerException: it.getString(bucketColumn) must not be null
	at com.slavabarkov.tidy.viewmodels.ORTImageViewModel$generateIndex$1.invokeSuspend(ORTImageViewModel.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e203a28, Dispatchers.Main]

**Comment by lone-faerie** [comment]
See https://github.com/slavabarkov/tidy/issues/28#issuecomment-2461169323

I fixed this by deleting any pictures in the root directory  (/storage/emulated/0)
