### ISSUE TITLE
crash on loading

### ISSUE THREAD

**Issue by lu-ckystars** [slavabarkov/tidy#22]
FATAL EXCEPTION: main
Process: com.slavabarkov.tidy, PID: 19465
java.lang.NullPointerException: it.getString(bucketColumn) must not be null
	at com.slavabarkov.tidy.viewmodels.ORTImageViewModel$generateIndex$1.invokeSuspend(ORTImageViewModel.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5e313e, Dispatchers.Main]

>I've got lots more logs from this but I don't feel comfortable sharing them on here, email me at alienmode@disroot.org if you would like them

**Comment by lone-faerie** [comment]
See https://github.com/slavabarkov/tidy/issues/28#issuecomment-2461169323

I fixed this by deleting any pictures in the root directory  (/storage/emulated/0)
