### ISSUE TITLE
App crashes on first launch

### ISSUE THREAD

**Issue by pogue** [slavabarkov/tidy#28]
I installed the app from F-Droid, version 1.1 and it starts to go through the scanning but immediately crashes. I manually gave the app permissions to Photos & Media before launching (why doesn't it pop up to prompt to request permissions?) and same problem. Uninstalled/reinstalled same problem.

Would saving a logcat output help?

I'm on a Samsung Galaxy S23+ OneUI 6.1 Android 14.

This app sounds like a great idea & I'd love to see it working.
![Screenshot_20240914_020002_Device care](https://github.com/user-attachments/assets/347d9faf-366a-496d-b5cb-2fe46567a4de)

**Comment by AshwinSoni-01** [comment]
It's also crashing for me during file indexing at around 50%.

**Comment by JorG941** [comment]
Happens the same to me (S21 FE Exynos, One UI 5.1, Android 13). It crashes at 96%.

**Comment by Rudrajarvis** [comment]
Experiencing same with my Redmi note 10S.

**Comment by lone-faerie** [comment]
I was having this issue too and this was the logcat message I was getting. I managed to work around it by deleting any pictures from my storage root directory (i.e. /storage/emulated/0) and now the app works.

`FATAL EXCEPTION: main
Process: com.slavabarkov.tidy, PID: 7008
java.lang.NullPointerException: it.getString(bucketColumn) must not be null
	at com.slavabarkov.tidy.viewmodels.ORTImageViewModel$generateIndex$1.invokeSuspend(ORTImageViewModel.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@42aa86d, Dispatchers.Main]`
