### ISSUE TITLE
App crashes during indexing

### ISSUE THREAD

**Issue by MK73DS** [slavabarkov/tidy#5]
Hello,

First, I want to say that I'm not an advanced user able to debug and fix bugs, I just downloaded the app from F-droid (version 1.1) and couldn't use it.

During the initial indexing, the app crashes at around 22%. If I launch it again, it goes very fast to that 22% and crash again. Maybe it hits a corrupted picture somewhere in my gallery that I'm unaware of, I don't know. I have a lot of pictures, around 10k, so maybe I'm hitting a limit?
Is there a way to enable some kind of logs to share?

My device information:
Sony Xperia 1 III
Android 13
Snapdragon 888

Thank you very much.

**Comment by gardockt** [comment]
Same here - it indeed seems to be linked to corruption.

Stack trace (captured with [Scoop](https://github.com/TacoTheDank/Scoop)):

```
java.io.IOException: read failed: EIO (I/O error)
	at libcore.io.IoBridge.read(IoBridge.java:511)
	at java.io.FileInputStream.read(FileInputStream.java:307)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:942)
	at java.io.FileInputStream.read(FileInputStream.java:276)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:933)
	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:110)
	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
	at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:136)
	at com.slavabarkov.tidy.viewmodels.ORTImageViewModel$generateIndex$1.invokeSuspend(ORTImageViewModel.kt:77)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c18c87c, Dispatchers.Main]
Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:184)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:254)
	at libcore.io.IoBridge.read(IoBridge.java:501)
	... 17 more
```

**Comment by slavabarkov** [comment]
@MK73DS @gardockt  Thank you for the reports! I'll try to fix it when I have a little bit more free time.

**Comment by Ingegneus** [comment]
For me it crashes at about 57%

**Comment by TheMemeSniper** [comment]
this happens to me at 4%, also using f-droid 1.1

i'm using a pixel 6a

**Comment by stilez** [comment]
**Crashes at start of indexing. Hopeful that this is all you need**


Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
[Device Brand]: samsung
[Device Model]: SM-N976B
[Display]: TQ3A.230901.001 dev-keys
[Android Version]: 13 AOSP (iodé tech)
[Android API Level]: 33
[System Locale]: en_GB
[Process ID]: 27190
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.slavabarkov.tidy
[Version Name]: 1.1
[Version Code]: 2
[Target SDK]: 33
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2023-12-27T05:41:28.694
[Stack Trace]:
java.lang.NullPointerException: it.getString(bucketColumn) must not be null
	at com.slavabarkov.tidy.viewmodels.ORTImageViewModel$generateIndex$1.invokeSuspend(ORTImageViewModel.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@db2ff82, Dispatchers.Main]

**Comment by sonalder-darlene** [comment]
Same on my Pixel 6A (GrapheneOS based on Android 14) with the F-Droid version it keeps crashing at around 46% of my image index at the first launch and when I relaunch the app after it crashed. Tried to clear cache, clear data but it always crash before the completing the first half. Same with the GitHub APK unfortunately.
